######
#
# A simple Makefile
#
######

TEMPOPT= \
$(TEMPTORY)/bin/tempopt

######

all:: test00
all:: test01
all:: test02

######

test00: test00.dats; $(TEMPOPT) -tc -d $<
test01: test01.dats; $(TEMPOPT) -tc -d $<
test02: test02.dats; $(TEMPOPT) -tc -d $<

###### end of [Makefile] ######
