######
#
# A simple Makefile
#
######

all:: ; \
make -C dirent -f Makefile all
all:: ; \
make -C search -f Makefile all

######

testall:: ; \
make -C dirent -f Makefile testall
testall:: ; \
make -C search -f Makefile testall

######

cleanall:: ; \
make -C dirent -f Makefile cleanall
testall:: ; \
make -C search -f Makefile cleanall

###### end of [Makefile] ######
